package com.companion.mobile;
import android.app.*;import android.content.*;import android.net.*;import android.os.*;import java.util.concurrent.*;
public class ControlSatelliteService extends Service {
 private static final String CHANNEL="companion_satellite";private static final ConcurrentHashMap<Integer,Session> sessions=new ConcurrentHashMap<>();private static final ConcurrentHashMap<Integer,Boolean> pressed=new ConcurrentHashMap<>();
 private final Handler networkHandler=new Handler(Looper.getMainLooper());private ConnectivityManager.NetworkCallback networkCallback;private final Runnable reconnectAll=()->{ConnectivityManager cm=getSystemService(ConnectivityManager.class);Network active=cm.getActiveNetwork();NetworkCapabilities caps=active==null?null:cm.getNetworkCapabilities(active);boolean wifi=caps!=null&&caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI);for(Session s:sessions.values())s.client.setWifiNetwork(wifi);};
 static class Session{final String endpoint;final SatelliteClient client;Session(String e,SatelliteClient c){endpoint=e;client=c;}}
 public static void startAll(Context c){Intent i=new Intent(c,ControlSatelliteService.class).setAction("all");start(c,i);}
 public static void startSlot(Context c,int slot){Intent i=new Intent(c,ControlSatelliteService.class).setAction("slot").putExtra("slot",slot);start(c,i);}
 public static void stopSlot(int slot){Session s=sessions.remove(slot);pressed.remove(slot);if(s!=null)s.client.stop();}
 private static void start(Context c,Intent i){if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 public static boolean isPressed(int slot){return Boolean.TRUE.equals(pressed.get(slot));}
 public static void press(Context c,int slot){Session s=sessions.get(slot);if(s!=null)s.client.press(0,0);else{Intent i=new Intent(c,ControlSatelliteService.class).setAction("press").putExtra("slot",slot);start(c,i);}}
 @Override public void onCreate(){super.onCreate();NotificationManager n=getSystemService(NotificationManager.class);if(Build.VERSION.SDK_INT>=26)n.createNotificationChannel(new NotificationChannel(CHANNEL,"Companion Satellite",NotificationManager.IMPORTANCE_LOW));PendingIntent p=PendingIntent.getActivity(this,2,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);startForeground(16621,new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.bitfocus_companion).setContentTitle("Companion 控制項").setContentText("12 個控制項正在同步").setContentIntent(p).setOngoing(true).build());ConnectivityManager cm=getSystemService(ConnectivityManager.class);networkCallback=new ConnectivityManager.NetworkCallback(){@Override public void onAvailable(Network network){networkHandler.removeCallbacks(reconnectAll);networkHandler.postDelayed(reconnectAll,350);}@Override public void onLost(Network network){networkHandler.removeCallbacks(reconnectAll);networkHandler.postDelayed(reconnectAll,350);}};cm.registerDefaultNetworkCallback(networkCallback);}
 @Override public int onStartCommand(Intent i,int flags,int id){if(i==null)return START_STICKY;if("all".equals(i.getAction()))for(int s=1;s<=12;s++)ensure(s);else{int slot=i.getIntExtra("slot",1);Session session=ensure(slot);if("press".equals(i.getAction())&&session!=null)session.client.press(0,0);}return START_STICKY;}
 private Session ensure(int slot){ControlStore.Control config=ControlStore.get(this,slot);if(!config.ready())return null;Session current=sessions.get(slot);if(current!=null&&current.endpoint.equals(config.host))return current;if(current!=null)current.client.stop();final SatelliteClient[] holder=new SatelliteClient[1];SatelliteClient client=new SatelliteClient(config.host,"android-tile-"+slot,"Android Tile "+slot,1,1,new SatelliteClient.Listener(){public void onState(int r,int c,String text,String color,String textColor,boolean down,android.graphics.Bitmap bitmap){pressed.put(slot,down);CompanionTileBase.refresh(ControlSatelliteService.this,slot);}public void onConnection(boolean connected){if(!connected)pressed.put(slot,false);CompanionTileBase.refresh(ControlSatelliteService.this,slot);}public void onDiagnostic(String message){getSharedPreferences("satellite_diagnostics",MODE_PRIVATE).edit().putString("control_"+slot,message).apply();}});holder[0]=client;Session made=new Session(config.host,client);sessions.put(slot,made);client.setWifiNetwork(isWifiActive());client.start();return made;}
 private boolean isWifiActive(){ConnectivityManager cm=getSystemService(ConnectivityManager.class);Network active=cm.getActiveNetwork();NetworkCapabilities caps=active==null?null:cm.getNetworkCapabilities(active);return caps!=null&&caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI);}
 @Override public void onDestroy(){if(networkCallback!=null)getSystemService(ConnectivityManager.class).unregisterNetworkCallback(networkCallback);networkHandler.removeCallbacks(reconnectAll);for(Session s:sessions.values())s.client.stop();sessions.clear();super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
