package com.companion.mobile;

import android.app.*;import android.content.*;import android.graphics.PixelFormat;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.ImageView;

public final class FloatingLauncherService extends Service {
    private static final String PREFS="floating_app_launcher",ENABLED="enabled";private WindowManager windows;private ImageView ball;private WindowManager.LayoutParams params;
    public static boolean enabled(Context c){return c.getSharedPreferences(PREFS,MODE_PRIVATE).getBoolean(ENABLED,false);}
    public static void setEnabled(Context c,boolean value){c.getSharedPreferences(PREFS,MODE_PRIVATE).edit().putBoolean(ENABLED,value).apply();if(value)start(c);else c.stopService(new Intent(c,FloatingLauncherService.class));}
    public static void restore(Context c){if(enabled(c)&&Settings.canDrawOverlays(c))start(c);}
    private static void start(Context c){Intent i=new Intent(c,FloatingLauncherService.class);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
    @Override public void onCreate(){super.onCreate();windows=(WindowManager)getSystemService(WINDOW_SERVICE);if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel("companion_launcher_ball","Companion 啟動球",NotificationManager.IMPORTANCE_LOW));PendingIntent open=PendingIntent.getActivity(this,16624,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);startForeground(16624,new Notification.Builder(this,"companion_launcher_ball").setSmallIcon(R.drawable.companion_control).setContentTitle("Companion 啟動球").setContentText("點一下即可開啟 Companion App").setContentIntent(open).setOngoing(true).build());showBall();}
    private void showBall(){if(ball!=null||!Settings.canDrawOverlays(this))return;android.content.SharedPreferences p=getSharedPreferences(PREFS,MODE_PRIVATE);ball=new ImageView(this);ball.setImageResource(R.drawable.bitfocus_companion);ball.setScaleType(ImageView.ScaleType.FIT_CENTER);ball.setPadding(dp(5),dp(5),dp(5),dp(5));int size=dp(64);params=new WindowManager.LayoutParams(size,size,Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);params.gravity=Gravity.TOP|Gravity.START;params.x=p.getInt("x",24);params.y=p.getInt("y",320);ball.setOnTouchListener(new View.OnTouchListener(){float downX,downY;int startX,startY;boolean moving;public boolean onTouch(View v,MotionEvent e){float dx=e.getRawX()-downX,dy=e.getRawY()-downY;switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:downX=e.getRawX();downY=e.getRawY();startX=params.x;startY=params.y;moving=false;v.animate().scaleX(.93f).scaleY(.93f).setDuration(70).start();return true;case MotionEvent.ACTION_MOVE:if(Math.abs(dx)>dp(8)||Math.abs(dy)>dp(8)){moving=true;params.x=Math.max(0,Math.min(startX+(int)dx,getResources().getDisplayMetrics().widthPixels-v.getWidth()));params.y=Math.max(0,Math.min(startY+(int)dy,getResources().getDisplayMetrics().heightPixels-v.getHeight()));windows.updateViewLayout(v,params);}return true;case MotionEvent.ACTION_UP:v.animate().scaleX(1).scaleY(1).setDuration(70).start();if(moving)p.edit().putInt("x",params.x).putInt("y",params.y).apply();else{Intent open=new Intent(FloatingLauncherService.this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);startActivity(open);}return true;case MotionEvent.ACTION_CANCEL:v.animate().scaleX(1).scaleY(1).setDuration(70).start();return true;}return true;}});windows.addView(ball,params);}
    private int dp(int value){return(int)(value*getResources().getDisplayMetrics().density+.5f);}
    @Override public void onDestroy(){if(ball!=null)try{windows.removeView(ball);}catch(Exception ignored){}ball=null;super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
