package com.companion.mobile;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;

public final class FloatingControlService extends Service {
 private static final String CHANNEL="companion_floating",ACTION_STOP="floating.stop";private final ConcurrentHashMap<String,Bubble>bubbles=new ConcurrentHashMap<>();private WindowManager windows;private final Handler main=new Handler(Looper.getMainLooper());private final ExecutorService io=Executors.newFixedThreadPool(2);private ConnectivityManager.NetworkCallback networkCallback;
 private final class Bubble{
  final FloatingControlStore.Item item;final ImageView view;final WindowManager.LayoutParams params;final SatelliteClient client;boolean connected=true;String text="",bg="#1f2937",fg="#ffffff";boolean pressed,hasValue;float value;
  Bubble(FloatingControlStore.Item item){this.item=item;view=new ImageView(FloatingControlService.this);int length=dp(item.size),thickness=dp(Math.max(56,item.size/3));view.setScaleType(ImageView.ScaleType.FIT_XY);view.setBackgroundColor(Color.TRANSPARENT);view.setImageBitmap(item.fader?drawFader(this):drawFace(item.name,"#1f2937","#ffffff",false,item.circular));params=new WindowManager.LayoutParams(item.fader?(item.vertical?thickness:length):length,item.fader?(item.vertical?length:thickness):length,Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);params.gravity=Gravity.TOP|Gravity.START;params.x=item.x;params.y=item.y;view.setAlpha(item.opacity/100f);view.setOnTouchListener(new Touch(this));client=new SatelliteClient(item.host,"android-floating-"+item.id,item.fader?"Android Floating Fader":"Android Floating Rotary",1,1,new SatelliteClient.Listener(){public void onState(int r,int c,String t,String b,String f,boolean p,Bitmap bitmap){text=t==null?"":t;bg=b;fg=f;pressed=p;main.post(()->view.setImageBitmap(item.fader?drawFader(Bubble.this):(item.circular?circle(bitmap!=null?bitmap:drawFace(text,bg,fg,pressed,true)):roundedSquare(bitmap!=null?bitmap:drawFace(text,bg,fg,pressed,false)))));}public void onConnection(boolean state){connected=state;main.post(()->view.setAlpha((item.opacity/100f)*(state?1f:.62f)));}public void onDiagnostic(String message){getSharedPreferences("satellite_diagnostics",MODE_PRIVATE).edit().putString("floating_"+item.id,message).apply();}});}
  void start(){windows.addView(view,params);client.setWifiNetwork(isWifi());client.start();if(item.fader)poll();}void stop(){client.stop();try{windows.removeView(view);}catch(Exception ignored){}}
  void poll(){if(!bubbles.containsKey(item.id))return;io.execute(()->{try{float next=Float.parseFloat(readVariable(item).trim());if(!hasValue||next!=value){value=next;hasValue=true;main.post(()->view.setImageBitmap(drawFader(this)));}}catch(Exception ignored){}main.postDelayed(this::poll,750);});}
 }
 private final class Touch implements View.OnTouchListener{final Bubble b;float downX,downY;int startX,startY;long downAt;boolean moving;Touch(Bubble b){this.b=b;}public boolean onTouch(View v,MotionEvent e){float dx=e.getRawX()-downX,dy=e.getRawY()-downY;switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:downX=e.getRawX();downY=e.getRawY();startX=b.params.x;startY=b.params.y;downAt=System.currentTimeMillis();moving=false;v.animate().scaleX(.96f).scaleY(.96f).setDuration(70).start();return true;case MotionEvent.ACTION_MOVE:if(System.currentTimeMillis()-downAt>420&&(moving||Math.hypot(dx,dy)<dp(18))){moving=true;b.params.x=clamp(startX+(int)dx,0,screenWidth()-v.getWidth());b.params.y=clamp(startY+(int)dy,0,screenHeight()-v.getHeight());windows.updateViewLayout(v,b.params);}return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:v.animate().scaleX(1).scaleY(1).setDuration(70).start();if(moving)FloatingControlStore.position(FloatingControlService.this,b.item.id,b.params.x,b.params.y);else if(b.item.interactive&&e.getActionMasked()==MotionEvent.ACTION_UP){float delta=b.item.fader?(b.item.vertical?-dy:dx):dx;if(Math.abs(delta)>dp(18))b.client.rotate(0,0,delta<0?-Math.max(1,(int)(Math.abs(delta)/dp(18))):Math.max(1,(int)(Math.abs(delta)/dp(18))));else b.client.pressSatellite(0,0);}return true;}return true;}}
 public static void restore(Context c){if(Settings.canDrawOverlays(c)&&FloatingControlStore.enabled(c)&&!FloatingControlStore.all(c).isEmpty())refresh(c);}public static void refresh(Context c){Intent i=new Intent(c,FloatingControlService.class).setAction("floating.refresh");if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}public static void stopAll(Context c){c.startService(new Intent(c,FloatingControlService.class).setAction(ACTION_STOP));}
 @Override public void onCreate(){super.onCreate();windows=(WindowManager)getSystemService(WINDOW_SERVICE);NotificationManager n=getSystemService(NotificationManager.class);if(Build.VERSION.SDK_INT>=26)n.createNotificationChannel(new NotificationChannel(CHANNEL,"懸浮 Satellite 工具",NotificationManager.IMPORTANCE_LOW));PendingIntent open=PendingIntent.getActivity(this,16623,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);startForeground(16623,new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.companion_control).setContentTitle("Companion 懸浮工具").setContentText("正在即時同步 Satellite").setContentIntent(open).setOngoing(true).build());ConnectivityManager cm=getSystemService(ConnectivityManager.class);networkCallback=new ConnectivityManager.NetworkCallback(){@Override public void onAvailable(Network n){main.postDelayed(()->routeChanged(),350);}@Override public void onLost(Network n){main.postDelayed(()->routeChanged(),350);}};cm.registerDefaultNetworkCallback(networkCallback);}
 @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null&&ACTION_STOP.equals(i.getAction())){FloatingControlStore.setEnabled(this,false);stopSelf();return START_NOT_STICKY;}reconcile();return START_STICKY;}
 private void reconcile(){if(!Settings.canDrawOverlays(this)||!FloatingControlStore.enabled(this)){stopSelf();return;}HashSet<String>wanted=new HashSet<>();for(FloatingControlStore.Item item:FloatingControlStore.all(this)){wanted.add(item.id);Bubble old=bubbles.get(item.id);if(old!=null&&same(old.item,item))continue;if(old!=null)old.stop();Bubble made=new Bubble(item);bubbles.put(item.id,made);made.start();}for(String id:new ArrayList<>(bubbles.keySet()))if(!wanted.contains(id)){Bubble b=bubbles.remove(id);if(b!=null)b.stop();}if(bubbles.isEmpty())stopSelf();}
 private boolean same(FloatingControlStore.Item a,FloatingControlStore.Item b){return a.host.equals(b.host)&&a.name.equals(b.name)&&a.opacity==b.opacity&&a.interactive==b.interactive&&a.size==b.size&&a.circular==b.circular&&a.fader==b.fader&&a.vertical==b.vertical&&a.min==b.min&&a.max==b.max&&a.variable.equals(b.variable);}
 private void routeChanged(){boolean wifi=isWifi();for(Bubble b:bubbles.values())b.client.setWifiNetwork(wifi);}private boolean isWifi(){ConnectivityManager cm=getSystemService(ConnectivityManager.class);Network active=cm.getActiveNetwork();NetworkCapabilities caps=active==null?null:cm.getNetworkCapabilities(active);return caps!=null&&caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI);}
 private Bitmap drawFader(Bubble b){int w=b.item.vertical?180:520,h=b.item.vertical?520:180;Bitmap out=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(Color.argb(220,15,23,42));c.drawRoundRect(2,2,w-2,h-2,28,28,p);float ratio=b.hasValue?Math.max(0,Math.min(1,(b.value-b.item.min)/(b.item.max-b.item.min))):.5f;float x=b.item.vertical?w/2f:w*.12f+(w*.76f)*ratio,y=b.item.vertical?h*.88f-(h*.76f)*ratio:h/2f;p.setColor(Color.rgb(100,116,139));if(b.item.vertical)c.drawRoundRect(w*.46f,h*.10f,w*.54f,h*.90f,14,14,p);else c.drawRoundRect(w*.10f,h*.46f,w*.90f,h*.54f,14,14,p);float kw=b.item.vertical?w*.78f:w*.25f,kh=b.item.vertical?h*.18f:h*.72f;p.setColor(parse(b.bg,Color.rgb(37,99,235)));RectF knob=new RectF(x-kw/2,y-kh/2,x+kw/2,y+kh/2);c.drawRoundRect(knob,18,18,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(Color.rgb(148,163,184));c.drawRoundRect(knob,18,18,p);p.setStyle(Paint.Style.FILL);p.setColor(parse(b.fg,Color.WHITE));p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(Math.min(32,kh*.28f));String t=b.text.replace("\\n"," ");if(t.length()>12)t=t.substring(0,12);c.drawText(t,x,y+p.getTextSize()*.34f,p);return out;}
 private String readVariable(FloatingControlStore.Item item)throws Exception{String v=item.variable.trim();if(v.startsWith("$(")&&v.endsWith(")"))v=v.substring(2,v.length()-1);int colon=v.indexOf(':');if(colon<1)throw new IOException();String label=v.substring(0,colon),name=v.substring(colon+1),path="custom".equalsIgnoreCase(label)?"/api/custom-variable/"+enc(name)+"/value":"expression".equalsIgnoreCase(label)?"/api/variable/expression/"+enc(name)+"/value":"/api/variable/"+enc(label)+"/"+enc(name)+"/value";String base=isWifi()&&!item.lan.isEmpty()?item.lan:item.web;HttpURLConnection h=(HttpURLConnection)new URL(base.replaceAll("/+$","")+path).openConnection();h.setConnectTimeout(1200);h.setReadTimeout(1200);try(InputStream in=h.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[]buf=new byte[256];for(int n;(n=in.read(buf))>0;)out.write(buf,0,n);return new String(out.toByteArray(),StandardCharsets.UTF_8);}finally{h.disconnect();}}
 private String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8").replace("+","%20");}
 private Bitmap drawFace(String text,String bg,String fg,boolean pressed,boolean circular){int s=192;Bitmap b=Bitmap.createBitmap(s,s,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(parse(bg,Color.rgb(31,41,55)));RectF r=new RectF(4,4,s-4,s-4);if(circular)c.drawCircle(s/2f,s/2f,s/2f-4,p);else c.drawRoundRect(r,32,32,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(Color.rgb(148,163,184));if(circular)c.drawCircle(s/2f,s/2f,s/2f-5,p);else c.drawRoundRect(r,32,32,p);p.setStyle(Paint.Style.FILL);p.setColor(parse(fg,Color.WHITE));p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(34);String v=text==null?"":text.replace("\\n"," ");if(v.length()>10)v=v.substring(0,10);c.drawText(v,s/2f,s/2f+12,p);return b;}
 private Bitmap crop(Bitmap source,boolean circle){int s=Math.max(source.getWidth(),source.getHeight());Bitmap out=Bitmap.createBitmap(s,s,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);BitmapShader sh=new BitmapShader(source,Shader.TileMode.CLAMP,Shader.TileMode.CLAMP);Matrix m=new Matrix();float scale=Math.max((float)s/source.getWidth(),(float)s/source.getHeight());m.setScale(scale,scale);m.postTranslate((s-source.getWidth()*scale)/2f,(s-source.getHeight()*scale)/2f);sh.setLocalMatrix(m);p.setShader(sh);if(circle)c.drawCircle(s/2f,s/2f,s/2f-4,p);else c.drawRoundRect(4,4,s-4,s-4,s*.18f,s*.18f,p);return out;}private Bitmap circle(Bitmap b){return crop(b,true);}private Bitmap roundedSquare(Bitmap b){return crop(b,false);}
 private int parse(String s,int fallback){try{return Color.parseColor(s!=null&&!s.startsWith("#")?"#"+s:s);}catch(Exception e){return fallback;}}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private int screenWidth(){return getResources().getDisplayMetrics().widthPixels;}private int screenHeight(){return getResources().getDisplayMetrics().heightPixels;}private int clamp(int v,int min,int max){return Math.max(min,Math.min(v,max));}
 @Override public void onDestroy(){if(networkCallback!=null)getSystemService(ConnectivityManager.class).unregisterNetworkCallback(networkCallback);for(Bubble b:bubbles.values())b.stop();bubbles.clear();io.shutdownNow();main.removeCallbacksAndMessages(null);super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
