package com.companion.mobile;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;

public final class FloatingControlService extends Service {
    private static final String CHANNEL="companion_floating", ACTION_REFRESH="floating.refresh", ACTION_STOP="floating.stop";
    private final ConcurrentHashMap<String,Bubble> bubbles=new ConcurrentHashMap<>();private WindowManager windows;private final Handler main=new Handler(Looper.getMainLooper());private ConnectivityManager.NetworkCallback networkCallback;
    private final class Bubble {
        final FloatingControlStore.Item item;final ImageView view;final WindowManager.LayoutParams params;final SatelliteClient client;
        Bubble(FloatingControlStore.Item item){this.item=item;view=new ImageView(FloatingControlService.this);int size=dp(76);view.setScaleType(ImageView.ScaleType.CENTER_CROP);view.setPadding(dp(3),dp(3),dp(3),dp(3));view.setBackground(oval(Color.rgb(31,41,55),Color.rgb(148,163,184),2));view.setClipToOutline(true);view.setOutlineProvider(new ViewOutlineProvider(){@Override public void getOutline(View v,Outline o){o.setOval(0,0,v.getWidth(),v.getHeight());}});view.setImageBitmap(drawFace(item.name,null,"#1f2937","#ffffff",false));params=new WindowManager.LayoutParams(size,size,Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);params.gravity=Gravity.TOP|Gravity.START;params.x=item.x;params.y=item.y;view.setOnTouchListener(new RotaryTouch(this));client=new SatelliteClient(item.host,"android-floating-"+item.id,"Android Floating Rotary",1,1,new SatelliteClient.Listener(){public void onState(int row,int col,String text,String bg,String fg,boolean pressed,Bitmap bitmap){main.post(()->view.setImageBitmap(circle(bitmap!=null?bitmap:drawFace(text,null,bg,fg,pressed))));}public void onConnection(boolean connected){if(!connected)main.post(()->view.setAlpha(.62f));else main.post(()->view.setAlpha(1f));}public void onDiagnostic(String message){getSharedPreferences("satellite_diagnostics",MODE_PRIVATE).edit().putString("floating_"+item.id,message).apply();}});}
        void start(){windows.addView(view,params);client.setWifiNetwork(isWifi());client.start();}
        void stop(){client.stop();try{windows.removeView(view);}catch(Exception ignored){}}
    }
    private final class RotaryTouch implements View.OnTouchListener {
        final Bubble bubble;float downX,downY;int startX,startY;long downAt;boolean moving;
        RotaryTouch(Bubble bubble){this.bubble=bubble;}
        public boolean onTouch(View v,android.view.MotionEvent e){float dx=e.getRawX()-downX,dy=e.getRawY()-downY;switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:downX=e.getRawX();downY=e.getRawY();startX=bubble.params.x;startY=bubble.params.y;downAt=System.currentTimeMillis();moving=false;v.animate().scaleX(.94f).scaleY(.94f).setDuration(80).start();return true;case MotionEvent.ACTION_MOVE:if(moving||System.currentTimeMillis()-downAt>380){moving=true;bubble.params.x=clamp(startX+(int)dx,0,screenWidth()-v.getWidth());bubble.params.y=clamp(startY+(int)dy,0,screenHeight()-v.getHeight());windows.updateViewLayout(v,bubble.params);}return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:v.animate().scaleX(1).scaleY(1).setDuration(80).start();if(moving){FloatingControlStore.position(FloatingControlService.this,bubble.item.id,bubble.params.x,bubble.params.y);}else if(Math.abs(dx)>dp(24)&&Math.abs(dx)>Math.abs(dy)){bubble.client.rotate(0,0,dx<0?-1:1);}else if(e.getActionMasked()==MotionEvent.ACTION_UP){bubble.client.pressSatellite(0,0);}return true;}return true;}
    }
    public static void restore(Context c){if(Settings.canDrawOverlays(c)&&FloatingControlStore.enabled(c)&&!FloatingControlStore.all(c).isEmpty())refresh(c);}
    public static void refresh(Context c){Intent i=new Intent(c,FloatingControlService.class).setAction(ACTION_REFRESH);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
    public static void stopAll(Context c){c.startService(new Intent(c,FloatingControlService.class).setAction(ACTION_STOP));}
    @Override public void onCreate(){super.onCreate();windows=(WindowManager)getSystemService(WINDOW_SERVICE);NotificationManager n=getSystemService(NotificationManager.class);if(Build.VERSION.SDK_INT>=26)n.createNotificationChannel(new NotificationChannel(CHANNEL,"懸浮 Satellite 旋鈕",NotificationManager.IMPORTANCE_LOW));PendingIntent open=PendingIntent.getActivity(this,16623,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification notification=new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.companion_control).setContentTitle("Companion 懸浮旋鈕").setContentText("正在即時同步 Satellite 按鈕").setContentIntent(open).setOngoing(true).build();startForeground(16623,notification);ConnectivityManager cm=getSystemService(ConnectivityManager.class);networkCallback=new ConnectivityManager.NetworkCallback(){@Override public void onAvailable(Network n){main.postDelayed(()->routeChanged(),350);}@Override public void onLost(Network n){main.postDelayed(()->routeChanged(),350);}};cm.registerDefaultNetworkCallback(networkCallback);}
    @Override public int onStartCommand(Intent intent,int flags,int startId){if(intent!=null&&ACTION_STOP.equals(intent.getAction())){FloatingControlStore.setEnabled(this,false);stopSelf();return START_NOT_STICKY;}reconcile();return START_STICKY;}
    private void reconcile(){if(!Settings.canDrawOverlays(this)||!FloatingControlStore.enabled(this)){stopSelf();return;}HashSet<String>wanted=new HashSet<>();for(FloatingControlStore.Item item:FloatingControlStore.all(this)){wanted.add(item.id);Bubble old=bubbles.get(item.id);if(old!=null&&old.item.host.equals(item.host)&&old.item.name.equals(item.name))continue;if(old!=null){old.stop();bubbles.remove(item.id);}Bubble made=new Bubble(item);bubbles.put(item.id,made);made.start();}for(String id:new ArrayList<>(bubbles.keySet()))if(!wanted.contains(id)){Bubble b=bubbles.remove(id);if(b!=null)b.stop();}if(bubbles.isEmpty())stopSelf();}
    private void routeChanged(){boolean wifi=isWifi();for(Bubble b:bubbles.values())b.client.setWifiNetwork(wifi);}
    private boolean isWifi(){ConnectivityManager cm=getSystemService(ConnectivityManager.class);Network active=cm.getActiveNetwork();android.net.NetworkCapabilities caps=active==null?null:cm.getNetworkCapabilities(active);return caps!=null&&caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI);}
    private Bitmap drawFace(String text,Bitmap ignored,String bg,String fg,boolean pressed){int size=192;Bitmap b=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);int background=parse(bg,Color.rgb(31,41,55));if(pressed)background=blend(background,Color.WHITE,.18f);p.setColor(background);c.drawCircle(size/2f,size/2f,size/2f-4,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(Color.rgb(148,163,184));c.drawCircle(size/2f,size/2f,size/2f-5,p);p.setStyle(Paint.Style.FILL);p.setColor(parse(fg,Color.WHITE));p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(34);String value=text==null?"":text.replace("\\n"," ");if(value.length()>10)value=value.substring(0,10);c.drawText(value,size/2f,size/2f+12,p);return b;}
    private Bitmap circle(Bitmap source){int size=Math.max(source.getWidth(),source.getHeight());Bitmap out=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);BitmapShader shader=new BitmapShader(source,Shader.TileMode.CLAMP,Shader.TileMode.CLAMP);Matrix m=new Matrix();float scale=Math.max((float)size/source.getWidth(),(float)size/source.getHeight());m.setScale(scale,scale);m.postTranslate((size-source.getWidth()*scale)/2f,(size-source.getHeight()*scale)/2f);shader.setLocalMatrix(m);p.setShader(shader);c.drawCircle(size/2f,size/2f,size/2f-4,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(3,size/48f));p.setColor(Color.rgb(148,163,184));c.drawCircle(size/2f,size/2f,size/2f-5,p);return out;}
    private GradientDrawable oval(int fill,int stroke,int width){GradientDrawable d=new GradientDrawable();d.setShape(GradientDrawable.OVAL);d.setColor(fill);d.setStroke(dp(width),stroke);return d;}
    private int parse(String s,int fallback){try{return Color.parseColor(s!=null&&!s.startsWith("#")?"#"+s:s);}catch(Exception e){return fallback;}}private int blend(int a,int b,float t){return Color.rgb((int)(Color.red(a)*(1-t)+Color.red(b)*t),(int)(Color.green(a)*(1-t)+Color.green(b)*t),(int)(Color.blue(a)*(1-t)+Color.blue(b)*t));}private int dp(int value){return(int)(value*getResources().getDisplayMetrics().density+.5f);}private int screenWidth(){return getResources().getDisplayMetrics().widthPixels;}private int screenHeight(){return getResources().getDisplayMetrics().heightPixels;}private int clamp(int v,int min,int max){return Math.max(min,Math.min(v,max));}
    @Override public void onDestroy(){if(networkCallback!=null)getSystemService(ConnectivityManager.class).unregisterNetworkCallback(networkCallback);for(Bubble b:bubbles.values())b.stop();bubbles.clear();super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
