package com.companion.mobile;

import android.graphics.*;
import android.os.*;
import android.util.Base64;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;
import org.java_websocket.client.WebSocketClient;
import org.java_websocket.handshake.ServerHandshake;

public final class SatelliteClient {
    public interface Listener { void onState(int row,int column,String text,String color,String textColor,boolean pressed,Bitmap bitmap); void onConnection(boolean connected); default void onDiagnostic(String message){} }
    private final String endpoint; private final int rows,columns; private final String deviceId,name; private final Listener listener;
    private volatile boolean running,registered; private volatile String activeEndpoint; private volatile long forceRemoteUntil; private Socket socket; private OutputStream rawOut; private volatile WebSocketClient wsClient; private boolean websocket,rawWebsocket; private Thread worker; private final Map<String,String> controlIds=new ConcurrentHashMap<>(),locations=new ConcurrentHashMap<>(); private boolean added;
    private static final Pattern PARAM=Pattern.compile("([A-Za-z_]+)=(?:\\\"([^\\\"]*)\\\"|(\\S+))");
    public SatelliteClient(String url,String deviceId,String name,int rows,int columns,Listener listener){ this.endpoint=url;this.deviceId=deviceId;this.name=name;this.rows=rows;this.columns=columns;this.listener=listener; }
    public synchronized void start(){ if(running)return;running=true;worker=new Thread(this::loop,"Satellite-"+deviceId);worker.start(); }
    public synchronized void stop(){running=false;try{if(wsClient!=null)wsClient.close();}catch(Exception ignored){}try{if(socket!=null)socket.close();}catch(Exception ignored){} }
    public synchronized void reconnect(){if(!running)return;registered=false;try{if(wsClient!=null)wsClient.close();}catch(Exception ignored){}try{if(socket!=null)socket.close();}catch(Exception ignored){} }
    public void reconnectIfRouteChanged(){new Thread(()->{String current=activeEndpoint;String next=NetworkRoute.resolveSatellite(endpoint);if(current!=null&&!current.equals(next)){forceRemoteUntil=0;listener.onDiagnostic("網路已切換："+current+" → "+next);reconnect();}},"Satellite-Route-Check").start();}
    public void setWifiNetwork(boolean wifi){new Thread(()->{forceRemoteUntil=wifi?0:Long.MAX_VALUE;String current=activeEndpoint;String next=wifi?NetworkRoute.resolveSatellite(endpoint):NetworkRoute.remoteSatellite(endpoint);listener.onDiagnostic((wifi?"Wi-Fi：":"行動數據：")+"選擇 "+next);if(current!=null&&!current.equals(next))reconnect();},"Satellite-Network-Type").start();}
    private void loop(){while(running){try{String selectedEndpoint=System.currentTimeMillis()<forceRemoteUntil?NetworkRoute.remoteSatellite(endpoint):NetworkRoute.resolveSatellite(endpoint);activeEndpoint=selectedEndpoint;listener.onDiagnostic("連線中："+selectedEndpoint);websocket=selectedEndpoint.toLowerCase().startsWith("ws");rawWebsocket=false;added=false;controlIds.clear();rawOut=null;if(websocket)runWebSocket(selectedEndpoint);else runTcp(selectedEndpoint);}catch(Exception error){if(activeEndpoint!=null&&activeEndpoint.startsWith("tcp://")){forceRemoteUntil=System.currentTimeMillis()+30000;listener.onDiagnostic("區網 Satellite 失敗，改走網際網路");}else listener.onDiagnostic("連線失敗："+error.getClass().getSimpleName()+" "+String.valueOf(error.getMessage()));}finally{registered=false;rawWebsocket=false;activeEndpoint=null;listener.onConnection(false);try{if(wsClient!=null)wsClient.close();}catch(Exception ignored){}wsClient=null;try{if(socket!=null)socket.close();}catch(Exception ignored){}socket=null;rawOut=null;}if(running)try{Thread.sleep(1000);}catch(InterruptedException ignored){}}}
    private void runTcp(String selectedEndpoint)throws Exception{URL u=toUrl(selectedEndpoint);int port=u.getPort()>0?u.getPort():16622;socket=connectSocket(u.getHost(),port,false);socket.setKeepAlive(true);socket.setSoTimeout(6000);rawOut=socket.getOutputStream();InputStream input=socket.getInputStream();Socket liveSocket=socket;startPing(()->running&&socket==liveSocket&&!liveSocket.isClosed());listener.onDiagnostic("區網 TCP 已連線，等待註冊");listener.onConnection(true);BufferedReader in=new BufferedReader(new InputStreamReader(input,StandardCharsets.UTF_8));String line;while(running&&(line=in.readLine())!=null)handle(line);}
    private void runWebSocket(String selectedEndpoint)throws Exception{CountDownLatch closed=new CountDownLatch(1);final String[] failure={""};WebSocketClient client=new WebSocketClient(new URI(selectedEndpoint)){@Override public void onOpen(ServerHandshake handshake){listener.onDiagnostic((selectedEndpoint.startsWith("wss://")?"安全":"區網")+" WebSocket 已連線，等待 Companion 註冊");listener.onConnection(true);startPing(()->running&&wsClient==this&&isOpen());}@Override public void onMessage(String message){try{for(String line:message.split("\\r?\\n"))if(!line.isEmpty())handle(line);}catch(Exception error){listener.onDiagnostic("資料解析失敗："+String.valueOf(error.getMessage()));}}@Override public void onClose(int code,String reason,boolean remote){failure[0]="關閉碼 "+code+" "+reason;listener.onDiagnostic("WebSocket 已關閉："+failure[0]);closed.countDown();}@Override public void onError(Exception error){failure[0]=error.getClass().getSimpleName()+" "+String.valueOf(error.getMessage());listener.onDiagnostic("WebSocket 錯誤："+failure[0]);if(!isOpen())closed.countDown();}};client.setConnectionLostTimeout(4);wsClient=client;if(!client.connectBlocking(7,TimeUnit.SECONDS))throw new IOException("WebSocket connection failed"+(failure[0].isEmpty()?"":"："+failure[0]));while(running&&client.isOpen())closed.await(2,TimeUnit.SECONDS);}
    private void runLocalWebSocket(String selectedEndpoint)throws Exception{URL u=toUrl(selectedEndpoint);int port=u.getPort()>0?u.getPort():16623;socket=connectSocket(u.getHost(),port,false);socket.setKeepAlive(true);socket.setSoTimeout(8000);rawOut=socket.getOutputStream();InputStream input=socket.getInputStream();handshake(u,input);rawWebsocket=true;Socket liveSocket=socket;listener.onDiagnostic("區網 WebSocket "+u.getHost()+":"+port+" 已連線，等待註冊");listener.onConnection(true);startPing(()->running&&socket==liveSocket&&!liveSocket.isClosed());while(running&&socket==liveSocket&&!liveSocket.isClosed()){String message=readWs(input);if(message==null)break;for(String line:message.split("\\r?\\n"))if(!line.isEmpty())handle(line);}}
    private interface Alive{boolean get();}
    private void startPing(Alive alive){new Thread(()->{while(alive.get()){send("PING");try{Thread.sleep(1000);}catch(InterruptedException e){break;}}},"Satellite-Ping").start();}
    private Socket connectSocket(String host,int port,boolean tls)throws Exception{Socket transport=new Socket();transport.connect(new InetSocketAddress(host,port),5000);if(!tls)return transport;javax.net.ssl.SSLSocket ssl=(javax.net.ssl.SSLSocket)((javax.net.ssl.SSLSocketFactory)javax.net.ssl.SSLSocketFactory.getDefault()).createSocket(transport,host,port,true);javax.net.ssl.SSLParameters parameters=ssl.getSSLParameters();parameters.setEndpointIdentificationAlgorithm("HTTPS");ssl.setSSLParameters(parameters);ssl.startHandshake();return ssl;}
    private URL toUrl(String value)throws Exception{String v=value.trim();if(v.startsWith("ws://"))return new URL("http://"+v.substring(5));if(v.startsWith("wss://"))return new URL("https://"+v.substring(6));if(v.startsWith("tcp://"))return new URL("http://"+v.substring(6));if(v.startsWith("http://")||v.startsWith("https://")){URL h=new URL(v);return new URL(h.getProtocol(),h.getHost(),16622,"");}return new URL("http://"+v+":16622");}
    private void handshake(URL u,InputStream in)throws Exception{byte[] nonce=new byte[16];new java.security.SecureRandom().nextBytes(nonce);String key=Base64.encodeToString(nonce,Base64.NO_WRAP);String path=u.getPath().isEmpty()?"/":u.getPath();String host=u.getHost()+(u.getPort()>0?":"+u.getPort():"");String req="GET "+path+" HTTP/1.1\r\nHost: "+host+"\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: "+key+"\r\nSec-WebSocket-Version: 13\r\n\r\n";rawOut.write(req.getBytes(StandardCharsets.US_ASCII));rawOut.flush();ByteArrayOutputStream h=new ByteArrayOutputStream();int last=0,b;while((b=in.read())!=-1){h.write(b);last=((last<<8)|b)&0xffffffff;if(last==0x0d0a0d0a)break;if(h.size()>16384)throw new IOException("WebSocket header too large");}String header=h.toString("UTF-8");if(!header.startsWith("HTTP/1.1 101")&&!header.startsWith("HTTP/1.0 101"))throw new IOException("WebSocket upgrade failed");}
    private String readWs(InputStream in)throws Exception{int b1=in.read();if(b1<0)return null;int b2=in.read();if(b2<0)return null;int opcode=b1&15;long len=b2&127;if(len==126)len=((in.read()&255)<<8)|(in.read()&255);else if(len==127){len=0;for(int i=0;i<8;i++)len=(len<<8)|(in.read()&255);}byte[] mask=null;if((b2&128)!=0){mask=new byte[4];readFully(in,mask);}if(len>8_000_000)throw new IOException("WebSocket message too large");byte[] data=new byte[(int)len];readFully(in,data);if(mask!=null)for(int i=0;i<data.length;i++)data[i]^=mask[i%4];if(opcode==8)return null;if(opcode==9){writeWs(data,10);return "";}if(opcode!=1)return "";return new String(data,StandardCharsets.UTF_8);}
    private void readFully(InputStream in,byte[] data)throws IOException{int p=0,n;while(p<data.length&&(n=in.read(data,p,data.length-p))>0)p+=n;if(p<data.length)throw new EOFException();}
    private synchronized void writeWs(byte[] data,int opcode)throws IOException{byte[] mask=new byte[4];new java.security.SecureRandom().nextBytes(mask);ByteArrayOutputStream frame=new ByteArrayOutputStream();frame.write(0x80|opcode);int len=data.length;if(len<126)frame.write(0x80|len);else if(len<=65535){frame.write(0x80|126);frame.write((len>>8)&255);frame.write(len&255);}else{frame.write(0x80|127);long size=len;for(int i=7;i>=0;i--)frame.write((int)((size>>(8*i))&255));}frame.write(mask);for(int i=0;i<len;i++)frame.write(data[i]^mask[i%4]);rawOut.write(frame.toByteArray());rawOut.flush();}
    private Map<String,String> params(String line){HashMap<String,String> m=new HashMap<>();Matcher x=PARAM.matcher(line);while(x.find())m.put(x.group(1).toUpperCase(),x.group(2)!=null?x.group(2):x.group(3));return m;}
    private void handle(String line)throws Exception{int sp=line.indexOf(' ');String cmd=(sp<0?line:line.substring(0,sp)).toUpperCase();Map<String,String> p=params(line);if("PING".equals(cmd)){send("PONG"+(sp<0?"":" "+line.substring(sp+1)));return;}if("ERROR".equals(cmd)){listener.onDiagnostic("Companion 回覆錯誤："+line);return;}if("BEGIN".equals(cmd)){registered=false;added=false;listener.onDiagnostic("已收到 Companion BEGIN，準備註冊");new Handler(Looper.getMainLooper()).postDelayed(this::addDevice,300);return;}if("CAPS".equals(cmd)){new Handler(Looper.getMainLooper()).postDelayed(this::addDevice,300);return;}if("ADD-DEVICE".equals(cmd)&&deviceId.equals(p.get("DEVICEID"))){registered=line.toUpperCase().contains(" OK ");listener.onDiagnostic(registered?"Satellite Online":"註冊失敗："+line);return;}if("KEY-STATE".equals(cmd)&&deviceId.equals(p.get("DEVICEID"))){registered=true;listener.onDiagnostic("Satellite Online，KEY-STATE 正常");String key=p.get("KEY"),cid=p.get("CONTROLID");int r=0,c=0;if(key!=null&&key.contains("/")){String[] a=key.split("/");r=Integer.parseInt(a[0]);c=Integer.parseInt(a[1]);}else if(cid!=null&&cid.contains("/")){String[] a=cid.split("/");r=Integer.parseInt(a[0]);c=Integer.parseInt(a[1]);}String localKey=r+"/"+c;if(cid!=null)controlIds.put(localKey,cid);if(p.get("LOCATION")!=null)locations.put(localKey,p.get("LOCATION"));String text=decodeText(p.get("TEXT"));Bitmap image=decodeBitmap(p.get("BITMAP"));listener.onState(r,c,text,p.get("COLOR"),p.get("TEXTCOLOR"),"1".equals(p.get("PRESSED")),image);} }
    private String decodeText(String s){if(s==null)return "";try{return new String(Base64.decode(s,Base64.DEFAULT),StandardCharsets.UTF_8);}catch(Exception e){return "";}}
    private Bitmap decodeBitmap(String s){if(s==null)return null;try{String data=s.contains(",")?s.substring(s.indexOf(',')+1):s;byte[] b=Base64.decode(data,Base64.DEFAULT);Bitmap compressed=BitmapFactory.decodeByteArray(b,0,b.length);if(compressed!=null)return compressed;if(b.length==72*72*3){int[] px=new int[72*72];for(int i=0;i<px.length;i++)px[i]=Color.rgb(b[i*3]&255,b[i*3+1]&255,b[i*3+2]&255);return Bitmap.createBitmap(px,72,72,Bitmap.Config.ARGB_8888);}}catch(Exception ignored){}return null;}
    private synchronized void addDevice(){if(added||(rawOut==null&&(wsClient==null||!wsClient.isOpen())))return;try{JSONObject manifest=new JSONObject(),styles=new JSONObject(),def=new JSONObject(),bitmap=new JSONObject();bitmap.put("w",288);bitmap.put("h",232);def.put("bitmap",bitmap);def.put("text",true);def.put("textStyle",true);def.put("colors","hex");styles.put("default",def);JSONObject controls=new JSONObject();for(int r=0;r<rows;r++)for(int c=0;c<columns;c++){JSONObject d=new JSONObject();d.put("row",r);d.put("column",c);controls.put(r+"/"+c,d);}manifest.put("stylePresets",styles);manifest.put("controls",controls);String layout=Base64.encodeToString(manifest.toString().getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);send("ADD-DEVICE DEVICEID=\""+deviceId+"\" LAYOUT_MANIFEST=\""+layout+"\" PRODUCT_NAME=\""+name+"\" VARIABLES=\"W10=\" BRIGHTNESS=0 PINCODE_LOCK=\"FULL\" SERIAL=\""+deviceId+"\" SERIAL_IS_UNIQUE=1 BITMAP_FORMAT=\"png\"");added=true;listener.onDiagnostic("已送出 ADD-DEVICE，等待 Companion 回覆");new Handler(Looper.getMainLooper()).postDelayed(()->{if(running&&!registered&&(rawOut!=null||(wsClient!=null&&wsClient.isOpen()))){added=false;listener.onDiagnostic("舊連線尚未釋放，重新註冊");addDevice();}},3000);}catch(Exception error){listener.onDiagnostic("建立註冊資料失敗："+String.valueOf(error.getMessage()));} }
    private synchronized void send(String s){try{byte[] data=(s+"\n").getBytes(StandardCharsets.UTF_8);if(rawWebsocket&&rawOut!=null){writeWs(data,1);return;}if(websocket&&wsClient!=null&&wsClient.isOpen()){wsClient.send(s+"\n");return;}if(rawOut!=null){rawOut.write(data);rawOut.flush();}}catch(Exception ignored){registered=false;try{if(wsClient!=null)wsClient.close();}catch(Exception ignoredWs){}try{if(socket!=null)socket.close();}catch(Exception ignoredClose){}} }
    public void press(int row,int column){pressSatellite(row,column);}
    public void pressSatellite(int row,int column){String key=row+"/"+column,cid=controlIds.getOrDefault(key,key);send("KEY-PRESS DEVICEID=\""+deviceId+"\" CONTROLID=\""+cid+"\" KEY=\""+key+"\" PRESSED=1");new Handler(Looper.getMainLooper()).postDelayed(()->send("KEY-PRESS DEVICEID=\""+deviceId+"\" CONTROLID=\""+cid+"\" KEY=\""+key+"\" PRESSED=0"),80);}
    public void keyDown(int row,int column){String key=row+"/"+column,cid=controlIds.getOrDefault(key,key);send("KEY-PRESS DEVICEID=\""+deviceId+"\" CONTROLID=\""+cid+"\" KEY=\""+key+"\" PRESSED=1");}
    public void keyUp(int row,int column){String key=row+"/"+column,cid=controlIds.getOrDefault(key,key);send("KEY-PRESS DEVICEID=\""+deviceId+"\" CONTROLID=\""+cid+"\" KEY=\""+key+"\" PRESSED=0");}
    public void rotate(int row,int column,int direction){String key=row+"/"+column,cid=controlIds.getOrDefault(key,key);int amount=direction==0?-1:direction;send("KEY-ROTATE DEVICEID=\""+deviceId+"\" CONTROLID=\""+cid+"\" KEY=\""+key+"\" DIRECTION="+amount);}
    private void httpPress(String location){new Thread(()->{try{String[] p=location.split("/");boolean lan=activeEndpoint!=null&&activeEndpoint.startsWith("tcp://");String base=NetworkRoute.resolveWebFast(endpoint,lan);HttpURLConnection c=(HttpURLConnection)new URL(base+"/api/location/"+p[0]+"/"+p[1]+"/"+p[2]+"/press").openConnection();c.setRequestMethod("POST");c.setConnectTimeout(2500);c.setReadTimeout(2500);c.setDoOutput(true);c.getOutputStream().close();c.getResponseCode();c.disconnect();}catch(Exception ignored){}},"Companion-Press").start();}
}
