package com.companion.mobile;
import android.app.*;import android.appwidget.*;import android.content.*;import android.graphics.*;import android.os.*;import android.widget.RemoteViews;import java.util.concurrent.*;import java.util.*;
public class WidgetSatelliteService extends Service {
 private static final String CHANNEL="companion_satellite";private static final ConcurrentHashMap<Integer,Session> sessions=new ConcurrentHashMap<>();
 private final Handler networkHandler=new Handler(Looper.getMainLooper());private android.net.ConnectivityManager.NetworkCallback networkCallback;private final Runnable reconnectAll=()->{android.net.ConnectivityManager cm=getSystemService(android.net.ConnectivityManager.class);android.net.Network active=cm.getActiveNetwork();android.net.NetworkCapabilities caps=active==null?null:cm.getNetworkCapabilities(active);boolean wifi=caps!=null&&caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI);for(Session s:sessions.values())s.client.setWifiNetwork(wifi);};
 static class Session{final int id,rows,cols;final Bitmap[] images=new Bitmap[16];final SatelliteClient client;Session(int id,int r,int c,SatelliteClient x){this.id=id;rows=r;cols=c;client=x;}}
 public static void start(Context c,int id){Intent i=new Intent(c,WidgetSatelliteService.class).setAction("start").putExtra("widget",id);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 public static void stopWidget(int id){Session s=sessions.remove(id);if(s!=null)s.client.stop();}
 public static void press(Context c,int id,int row,int col){Session s=sessions.get(id);if(s!=null)s.client.press(row,col);else{Intent i=new Intent(c,WidgetSatelliteService.class).setAction("press").putExtra("widget",id).putExtra("row",row).putExtra("column",col);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}}
 public static void rotate(Context c,int id,int direction){rotate(c,id,0,0,direction);}
 public static void rotate(Context c,int id,int row,int col,int direction){Session s=sessions.get(id);if(s!=null)s.client.rotate(row,col,direction);else{Intent i=new Intent(c,WidgetSatelliteService.class).setAction("rotate").putExtra("widget",id).putExtra("row",row).putExtra("column",col).putExtra("direction",direction);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}}
 @Override public void onCreate(){super.onCreate();NotificationManager n=getSystemService(NotificationManager.class);if(Build.VERSION.SDK_INT>=26)n.createNotificationChannel(new NotificationChannel(CHANNEL,"Companion Satellite",NotificationManager.IMPORTANCE_LOW));Intent open=new Intent(this,MainActivity.class);PendingIntent p=PendingIntent.getActivity(this,1,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification notification=new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.bitfocus_companion).setContentTitle("Companion Satellite").setContentText("Widget 正在與 Companion 即時同步").setContentIntent(p).setOngoing(true).build();startForeground(16622,notification);android.net.ConnectivityManager cm=getSystemService(android.net.ConnectivityManager.class);networkCallback=new android.net.ConnectivityManager.NetworkCallback(){@Override public void onAvailable(android.net.Network network){networkHandler.removeCallbacks(reconnectAll);networkHandler.postDelayed(reconnectAll,350);}@Override public void onLost(android.net.Network network){networkHandler.removeCallbacks(reconnectAll);networkHandler.postDelayed(reconnectAll,350);}};cm.registerDefaultNetworkCallback(networkCallback);}
 @Override public int onStartCommand(Intent i,int flags,int startId){if(i==null)return START_STICKY;int id=i.getIntExtra("widget",-1);if(id<0)return START_STICKY;Session s=ensure(id);if("press".equals(i.getAction())&&s!=null)s.client.press(i.getIntExtra("row",0),i.getIntExtra("column",0));else if("rotate".equals(i.getAction())&&s!=null)s.client.rotate(i.getIntExtra("row",0),i.getIntExtra("column",0),i.getIntExtra("direction",1));return START_STICKY;}
 private Session ensure(int id){Session current=sessions.get(id);if(current!=null)return current;String host=WidgetPrefs.host(this,id);if(host.isEmpty())return null;int rows=WidgetPrefs.rows(this,id),cols=WidgetPrefs.cols(this,id);final Session[] holder=new Session[1];SatelliteClient client=new SatelliteClient(host,"android-widget-"+id,"Android Widget "+cols+"x"+rows,rows,cols,new SatelliteClient.Listener(){public void onState(int row,int col,String text,String color,String textColor,boolean pressed,Bitmap bitmap){Session s=holder[0];if(s==null)return;int index=row*cols+col;if(index<0||index>=s.images.length)return;s.images[index]=squareCard(bitmap!=null?bitmap:draw(text,color,textColor,pressed));render(s);}public void onConnection(boolean connected){}public void onDiagnostic(String message){getSharedPreferences("satellite_diagnostics",MODE_PRIVATE).edit().putString("widget_"+id,message).apply();}});Session made=new Session(id,rows,cols,client);holder[0]=made;Session old=sessions.putIfAbsent(id,made);if(old!=null)return old;render(made);client.setWifiNetwork(isWifiActive());client.start();return made;}
 private boolean isWifiActive(){android.net.ConnectivityManager cm=getSystemService(android.net.ConnectivityManager.class);android.net.Network active=cm.getActiveNetwork();android.net.NetworkCapabilities caps=active==null?null:cm.getNetworkCapabilities(active);return caps!=null&&caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI);}
 private Bitmap draw(String text,String bg,String fg,boolean pressed){int w=288,h=232;Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);Paint shape=new Paint(Paint.ANTI_ALIAS_FLAG);int background=parse(bg,Color.rgb(30,41,59));if(pressed)background=blend(background,Color.WHITE,0.18f);shape.setColor(background);c.drawRoundRect(0,0,w,h,20,20,shape);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(parse(fg,Color.WHITE));p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(48);String[] lines=(text==null?"":text.replace("\\n","\n")).split("\n");float y=h/2f-(lines.length-1)*29;for(String line:lines){c.drawText(line.length()>14?line.substring(0,14):line,w/2f,y,p);y+=58;}return b;}
 private Bitmap squareCard(Bitmap source){if(source==null)return null;int size=Math.max(source.getWidth(),source.getHeight());Bitmap square=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(square);Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);int edge=source.getPixel(Math.min(2,source.getWidth()-1),Math.min(2,source.getHeight()-1));paint.setColor(edge);canvas.drawRect(0,0,size,size,paint);float scale=Math.min((float)size/source.getWidth(),(float)size/source.getHeight());float w=source.getWidth()*scale,h=source.getHeight()*scale;android.graphics.RectF imageDst=new android.graphics.RectF((size-w)/2f,(size-h)/2f,(size+w)/2f,(size+h)/2f);canvas.drawBitmap(source,null,imageDst,paint);Bitmap out=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas clipped=new Canvas(out);float radius=size/12f;clipped.drawRoundRect(2,2,size-2,size-2,radius,radius,paint);paint.setXfermode(new android.graphics.PorterDuffXfermode(android.graphics.PorterDuff.Mode.SRC_IN));clipped.drawBitmap(square,0,0,paint);paint.setXfermode(null);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(Math.max(3,size/72f));paint.setColor(Color.rgb(75,85,99));clipped.drawRoundRect(2,2,size-2,size-2,radius,radius,paint);return out;}
 private int parse(String s,int fallback){try{return Color.parseColor(s!=null&&!s.startsWith("#")?"#"+s:s);}catch(Exception e){return fallback;}}private int blend(int a,int b,float t){return Color.rgb((int)(Color.red(a)*(1-t)+Color.red(b)*t),(int)(Color.green(a)*(1-t)+Color.green(b)*t),(int)(Color.blue(a)*(1-t)+Color.blue(b)*t));}
 private void render(Session s){String mode=WidgetPrefs.mode(this,s.id);if("rotary1".equals(mode)){renderRotary(s);return;}if("rotary4".equals(mode)){renderRotaryGrid(s,false);return;}if("mixed4x4".equals(mode)){renderRotaryGrid(s,true);return;}RemoteViews v=CompanionWidgetBase.baseViews(this,s.rows,s.cols);Class<?> receiver=s.rows==4&&s.cols==1?CompanionWidget1x4.class:s.rows==4?CompanionWidget4x4.class:s.rows==3?CompanionWidget4x3.class:s.rows==2&&s.cols==4?CompanionWidget4x2.class:s.rows==2&&s.cols==3?CompanionWidget3x2.class:s.rows==2?CompanionWidget2x2.class:s.cols==4?CompanionWidget4x1.class:CompanionWidget1x1.class;for(int i=0;i<s.rows*s.cols;i++){int viewId=CompanionWidgetBase.keyId(s.rows,s.cols,i);if(s.images[i]!=null)v.setImageViewBitmap(viewId,s.images[i]);bindPress(v,viewId,receiver,s.id,i/s.cols,i%s.cols,s.id*40+i);}AppWidgetManager.getInstance(this).updateAppWidget(s.id,v);}
 private void bindPress(RemoteViews v,int viewId,Class<?> receiver,int widget,int row,int col,int request){Intent press=new Intent(this,receiver).setAction("com.companion.mobile.WIDGET_PRESS").putExtra("widget",widget).putExtra("row",row).putExtra("column",col);v.setOnClickPendingIntent(viewId,PendingIntent.getBroadcast(this,request,press,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}
 private void renderRotaryGrid(Session s,boolean mixed){RemoteViews v=new RemoteViews(getPackageName(),mixed?R.layout.widget_mixed_4x4:R.layout.widget_rotary_4x1);Class<?> receiver=mixed?CompanionWidgetMixed4x4.class:CompanionWidgetRotary4x1.class;if(mixed)for(int i=0;i<12;i++){if(s.images[i]!=null)v.setImageViewBitmap(CompanionWidgetBase.KEYS[i],s.images[i]);bindPress(v,CompanionWidgetBase.KEYS[i],receiver,s.id,i/4,i%4,s.id*80+i);}int start=mixed?12:0,row=mixed?3:0;int[] images={R.id.rotary_image1,R.id.rotary_image2,R.id.rotary_image3,R.id.rotary_image4};int[] left={R.id.rotary_left1,R.id.rotary_left2,R.id.rotary_left3,R.id.rotary_left4};int[] press={R.id.rotary_press1,R.id.rotary_press2,R.id.rotary_press3,R.id.rotary_press4};int[] right={R.id.rotary_right1,R.id.rotary_right2,R.id.rotary_right3,R.id.rotary_right4};for(int col=0;col<4;col++){if(s.images[start+col]!=null)v.setImageViewBitmap(images[col],circleCard(s.images[start+col]));bindRotary(v,left[col],receiver,s.id,row,col,-1,s.id*100+col*3);bindRotary(v,press[col],receiver,s.id,row,col,0,s.id*100+col*3+1);bindRotary(v,right[col],receiver,s.id,row,col,1,s.id*100+col*3+2);}AppWidgetManager.getInstance(this).updateAppWidget(s.id,v);}
 private void bindRotary(RemoteViews v,int viewId,Class<?> receiver,int widget,int row,int col,int direction,int request){String action=direction==0?"com.companion.mobile.ROTARY_PRESS":"com.companion.mobile.ROTARY_ROTATE";Intent intent=new Intent(this,receiver).setAction(action).putExtra("widget",widget).putExtra("row",row).putExtra("column",col).putExtra("direction",direction);v.setOnClickPendingIntent(viewId,PendingIntent.getBroadcast(this,request,intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}
 private void renderRotary(Session s){RemoteViews v=new RemoteViews(getPackageName(),R.layout.widget_rotary);if(s.images[0]!=null)v.setImageViewBitmap(R.id.rotary_image,circleCard(s.images[0]));String[] actions={"com.companion.mobile.ROTARY_LEFT","com.companion.mobile.ROTARY_PRESS","com.companion.mobile.ROTARY_RIGHT"};int[] views={R.id.rotary_left,R.id.rotary_press,R.id.rotary_right};for(int i=0;i<3;i++){Intent intent=new Intent(this,CompanionWidgetRotary.class).setAction(actions[i]).putExtra("widget",s.id);v.setOnClickPendingIntent(views[i],PendingIntent.getBroadcast(this,s.id*30+i,intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}AppWidgetManager.getInstance(this).updateAppWidget(s.id,v);}
 private Bitmap circleCard(Bitmap source){int size=Math.max(source.getWidth(),source.getHeight());Bitmap out=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(out);Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setColor(Color.rgb(31,41,55));canvas.drawCircle(size/2f,size/2f,size/2f-3,paint);float scale=Math.min((float)size/source.getWidth(),(float)size/source.getHeight());float w=source.getWidth()*scale,h=source.getHeight()*scale;android.graphics.RectF dst=new android.graphics.RectF((size-w)/2f,(size-h)/2f,(size+w)/2f,(size+h)/2f);Bitmap layer=Bitmap.createBitmap(size,size,Bitmap.Config.ARGB_8888);Canvas lc=new Canvas(layer);lc.drawBitmap(source,null,dst,paint);paint.setXfermode(new android.graphics.PorterDuffXfermode(android.graphics.PorterDuff.Mode.SRC_IN));canvas.drawBitmap(layer,0,0,paint);paint.setXfermode(null);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(Math.max(4,size/48f));paint.setColor(Color.rgb(107,114,128));canvas.drawCircle(size/2f,size/2f,size/2f-4,paint);return out;}
 @Override public void onDestroy(){if(networkCallback!=null)getSystemService(android.net.ConnectivityManager.class).unregisterNetworkCallback(networkCallback);networkHandler.removeCallbacks(reconnectAll);for(Session s:sessions.values())s.client.stop();sessions.clear();super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
