package com.companion.mobile;

import android.app.*;import android.appwidget.*;import android.content.*;import android.os.*;import android.widget.*;import org.json.*;import java.util.*;

public class WidgetConfigActivity extends Activity {
 private int id=AppWidgetManager.INVALID_APPWIDGET_ID;private final ArrayList<String> routes=new ArrayList<>(),webUrls=new ArrayList<>(),lanUrls=new ArrayList<>();
 @Override public void onCreate(Bundle state){super.onCreate(state);setResult(RESULT_CANCELED);id=getIntent().getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id);AppWidgetProviderInfo info=AppWidgetManager.getInstance(this).getAppWidgetInfo(id);String provider=info==null?"":info.provider.getClassName(),mode=mode(provider);int rows=rows(provider),cols=cols(provider);boolean fader=mode.startsWith("fader");
  LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(40,50,40,30);TextView title=new TextView(this);title.setText(fader?"設定 Companion Satellite Fader":"設定 Companion Satellite Widget");title.setTextSize(21);box.addView(title);
  Spinner host=new Spinner(this);ArrayList<String> labels=new ArrayList<>();int selected=0;try{JSONArray a=new JSONArray(getSharedPreferences("companion_hosts",MODE_PRIVATE).getString("hosts","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);String web=o.getString("url"),lan=o.optString("lan",""),sat=MainActivity.Host.defaultSatellite(web),route=lan.isEmpty()?sat:NetworkRoute.auto(lan,sat);labels.add(o.getString("name")+" — 自動選擇區網／網際網路");routes.add(route);webUrls.add(web);lanUrls.add(lan);if(route.equals(WidgetPrefs.host(this,id)))selected=i;}}catch(Exception ignored){}if(labels.isEmpty()){labels.add("請先回 App 新增主機");routes.add("");webUrls.add("");lanUrls.add("");}host.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));host.setSelection(selected);box.addView(host);
  CheckBox interaction=new CheckBox(this);interaction.setText(fader?"允許旋轉與按下 Fader":"允許按下與旋轉");interaction.setChecked(WidgetPrefs.interactive(this,id));box.addView(interaction);TextView opacityLabel=new TextView(this);SeekBar opacity=new SeekBar(this);opacity.setMin(5);opacity.setMax(100);opacity.setProgress(WidgetPrefs.opacity(this,id));opacityLabel.setText("透明度："+opacity.getProgress()+"%");opacity.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int value,boolean user){opacityLabel.setText("透明度："+value+"%");}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});box.addView(opacityLabel);box.addView(opacity);
  Spinner direction=new Spinner(this);EditText minimum=new EditText(this),maximum=new EditText(this);EditText[] variables=new EditText[fader?cols:0];if(fader){TextView dl=new TextView(this);dl.setText("Fader 方向");box.addView(dl);direction.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"垂直（下減、上增）","水平（左減、右增）"}));direction.setSelection(WidgetPrefs.faderVertical(this,id)?0:1);box.addView(direction);minimum.setHint("最小值，例如 -60");maximum.setHint("最大值，例如 10");minimum.setInputType(8194);maximum.setInputType(8194);minimum.setText(number(WidgetPrefs.faderMin(this,id)));maximum.setText(number(WidgetPrefs.faderMax(this,id)));box.addView(minimum);box.addView(maximum);for(int i=0;i<cols;i++){variables[i]=new EditText(this);variables[i].setHint("Fader "+(i+1)+" 變數，例如 $(WiiM:volume)");variables[i].setSingleLine();variables[i].setText(WidgetPrefs.faderVariable(this,id,i));box.addView(variables[i]);}}
  TextView hint=new TextView(this);hint.setText(fader?"按鈕樣式與操作使用 Satellite；位置使用指定的 Companion 變數。桌面 Widget 不支援連續拖曳，請點擊滑軌兩端旋轉、點擊中間色塊按下。":"取消勾選後只顯示即時 Tally，不會送出操作。");hint.setPadding(0,8,0,18);box.addView(hint);Button save=new Button(this);save.setText(WidgetPrefs.host(this,id).isEmpty()?"連線並加入 Widget":"儲存設定");box.addView(save);ScrollView scroll=new ScrollView(this);scroll.addView(box);setContentView(scroll);
  save.setOnClickListener(v->{String route=routes.get(host.getSelectedItemPosition());if(route.isEmpty()){Toast.makeText(this,"請先在 Companion App 新增主機",Toast.LENGTH_LONG).show();return;}float min=0,max=100;if(fader)try{min=Float.parseFloat(minimum.getText().toString().trim());max=Float.parseFloat(maximum.getText().toString().trim());}catch(Exception e){Toast.makeText(this,"請輸入有效的最小值與最大值",Toast.LENGTH_LONG).show();return;}if(fader&&max<=min){Toast.makeText(this,"最大值必須大於最小值",Toast.LENGTH_LONG).show();return;}WidgetSatelliteService.stopWidget(id);WidgetPrefs.save(this,id,route,rows,cols,mode);WidgetPrefs.setInteractive(this,id,interaction.isChecked());WidgetPrefs.setOpacity(this,id,opacity.getProgress());if(fader){String[] vars=new String[cols];for(int i=0;i<cols;i++)vars[i]=variables[i].getText().toString().trim();WidgetPrefs.setFader(this,id,direction.getSelectedItemPosition()==0,min,max,webUrls.get(host.getSelectedItemPosition()),lanUrls.get(host.getSelectedItemPosition()),vars);}AppWidgetManager manager=AppWidgetManager.getInstance(this);if("rotary1".equals(mode))CompanionWidgetRotary.renderPlaceholder(this,manager,id);else if("grid".equals(mode))CompanionWidgetBase.renderPlaceholder(this,manager,id,rows,cols);else manager.updateAppWidget(id,new RemoteViews(getPackageName(),layout(mode,WidgetPrefs.faderVertical(this,id))));WidgetSatelliteService.start(this,id);setResult(RESULT_OK,new Intent().putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id));finish();});
 }
 private String mode(String n){if(n.endsWith("CompanionWidgetFader4x1"))return "fader4";if(n.endsWith("CompanionWidgetFader"))return "fader1";if(n.endsWith("CompanionWidgetRotary"))return "rotary1";if(n.endsWith("CompanionWidgetRotary4x1"))return "rotary4";if(n.endsWith("CompanionWidgetMixed4x4"))return "mixed4x4";return "grid";}
 private int rows(String n){return n.endsWith("CompanionWidget1x4")||n.endsWith("4x4")?4:n.endsWith("4x3")?3:n.endsWith("4x2")||n.endsWith("3x2")||n.endsWith("2x2")?2:1;}private int cols(String n){return n.endsWith("CompanionWidget1x4")?1:n.endsWith("2x2")?2:n.endsWith("3x2")?3:n.endsWith("4x1")||n.endsWith("4x2")||n.endsWith("4x3")||n.endsWith("4x4")?4:1;}
 private int layout(String mode,boolean vertical){if("fader4".equals(mode))return vertical?R.layout.widget_fader_4_vertical:R.layout.widget_fader_4_horizontal;if("fader1".equals(mode))return vertical?R.layout.widget_fader_1_vertical:R.layout.widget_fader_1_horizontal;return "rotary4".equals(mode)?R.layout.widget_rotary_4x1:R.layout.widget_mixed_4x4;}private String number(float v){return v==(long)v?Long.toString((long)v):Float.toString(v);}
}
